#!/system/bin/sh

echo '800000' > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo '320000' >/sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

#The frequency until which CPU is scaled up rapidly on screen-awake from sleep. Thereafter, scaling up is less aggressive.
echo "600000" > /sys/devices/system/cpu/cpufreq/smartass/awake_ideal_freq;

#The frequency until which CPU is scaled down rapidly when screen is turned off. 
echo "320000" > /sys/devices/system/cpu/cpufreq/smartass/sleep_ideal_freq;

#The frequency to set when waking up from sleep. When sleep_ideal_freq=0 this will have no effect
echo "800000" > /sys/devices/system/cpu/cpufreq/smartass/sleep_wakeup_freq

#Same as up_threshold
echo "85" > /sys/devices/system/cpu/cpufreq/smartass/max_cpu_load;

#Same as down_threshold
echo "40" > /sys/devices/system/cpu/cpufreq/smartass/min_cpu_load;

#Frequency when ramping up above the ideal frequency. Zero disables and causes to always jump straight to max frequency and when below the ideal frequency we always ramp up to the ideal freq
echo "200000" > /sys/devices/system/cpu/cpufreq/smartass/ramp_up_step;

#Frequency delta when ramping down below the ideal frequency. Zero disables and will calculate ramp down according to load heuristic. When above the ideal frequency we always ramp down to the ideal freq.
echo "120000" > /sys/devices/system/cpu/cpufreq/smartass/ramp_down_step;

#The minimum amount of time to spend at a frequency before we can ramp up.
echo "48000" > /sys/devices/system/cpu/cpufreq/smartass/up_rate_us

#The minimum amount of time to spend at a frequency before we can ramp down.
echo "49000" > /sys/devices/system/cpu/cpufreq/smartass/down_rate_us